/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.poo;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Adrian_Alejandro
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    private ArrayList<ImageIcon> imagenes = new ArrayList<>();

    public JFrame() {
        initComponents();
        setSize(636, 550);
        nueve.setVisible(false);
        setLocationRelativeTo(this);

        uno.setVisible(false);
        dos.setVisible(false);
        tres.setVisible(false);
        cuatro.setVisible(false);
        cinco.setVisible(false);
        seis.setVisible(false);
        siete.setVisible(false);
        ocho.setVisible(false);
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/9.jpg")));
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/8.jpg")));
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/7.jpg")));
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/6.jpg")));
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/5.jpg")));
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/4.jpg")));
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/3.jpg")));
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/2.jpg")));
        imagenes.add(new ImageIcon(getClass().getResource("/imagenes/1.jpg")));
        Collections.shuffle(imagenes);

        uno.setIcon(imagenes.get(0));
        dos.setIcon(imagenes.get(1));
        tres.setIcon(imagenes.get(2));
        cuatro.setIcon(imagenes.get(3));
        cinco.setIcon(imagenes.get(4));
        seis.setIcon(imagenes.get(5));
        siete.setIcon(imagenes.get(6));
        ocho.setIcon(imagenes.get(7));
        nueve.setIcon(imagenes.get(8));
        Rendirse.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        crono2 = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        perdio = new javax.swing.JLabel();
        perdio1 = new javax.swing.JLabel();
        Rendirse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PUZZLE");
        setBackground(new java.awt.Color(255, 204, 51));
        setMinimumSize(new java.awt.Dimension(636, 550));
        setSize(new java.awt.Dimension(636, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9.jpg"))); // NOI18N
        uno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uno.setMaximumSize(new java.awt.Dimension(35, 25));
        uno.setMinimumSize(new java.awt.Dimension(35, 25));
        uno.setName("Boton1"); // NOI18N
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        getContentPane().add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, 130));

        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8.jpg"))); // NOI18N
        dos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dos.setMaximumSize(new java.awt.Dimension(35, 25));
        dos.setMinimumSize(new java.awt.Dimension(35, 25));
        dos.setName("Boton2"); // NOI18N
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        getContentPane().add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 130));

        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7.jpg"))); // NOI18N
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tres.setMaximumSize(new java.awt.Dimension(35, 25));
        tres.setMinimumSize(new java.awt.Dimension(35, 25));
        tres.setName("Boton3"); // NOI18N
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        getContentPane().add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 130, 130));

        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6.jpg"))); // NOI18N
        cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuatro.setMaximumSize(new java.awt.Dimension(35, 25));
        cuatro.setMinimumSize(new java.awt.Dimension(35, 25));
        cuatro.setName("Boton4"); // NOI18N
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        getContentPane().add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, 130));

        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5.jpg"))); // NOI18N
        cinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cinco.setMaximumSize(new java.awt.Dimension(35, 25));
        cinco.setMinimumSize(new java.awt.Dimension(35, 25));
        cinco.setName("Boton5"); // NOI18N
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        getContentPane().add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 130, 130));

        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4.jpg"))); // NOI18N
        seis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seis.setMaximumSize(new java.awt.Dimension(35, 25));
        seis.setMinimumSize(new java.awt.Dimension(35, 25));
        seis.setName("Boton6"); // NOI18N
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        getContentPane().add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 130, 130));

        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3.jpg"))); // NOI18N
        siete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        siete.setMaximumSize(new java.awt.Dimension(35, 25));
        siete.setMinimumSize(new java.awt.Dimension(35, 25));
        siete.setName("Boton7"); // NOI18N
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        getContentPane().add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 130, 130));

        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.jpg"))); // NOI18N
        ocho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ocho.setMaximumSize(new java.awt.Dimension(35, 25));
        ocho.setMinimumSize(new java.awt.Dimension(35, 25));
        ocho.setName("Boton8"); // NOI18N
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        getContentPane().add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 130, 130));

        nueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.jpg"))); // NOI18N
        nueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nueve.setMaximumSize(new java.awt.Dimension(35, 25));
        nueve.setMinimumSize(new java.awt.Dimension(35, 25));
        nueve.setName("Boton9"); // NOI18N
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        getContentPane().add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 130, 130));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/galaxia efecto.jpg"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/galaxia efecto 2.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, 50));

        crono2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        crono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crono2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(crono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 90, 40));

        Iniciar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/galaxia efecto.jpg"))); // NOI18N
        Iniciar.setText("Iniciar");
        Iniciar.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        Iniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Iniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/galaxia efecto 2.jpg"))); // NOI18N
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, 50));

        perdio.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        perdio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(perdio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 90, 40));

        perdio1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        perdio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(perdio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 90, 40));

        Rendirse.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Rendirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/galaxia efecto.jpg"))); // NOI18N
        Rendirse.setText("Rendirse");
        Rendirse.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        Rendirse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Rendirse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/galaxia efecto 2.jpg"))); // NOI18N
        Rendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RendirseActionPerformed(evt);
            }
        });
        getContentPane().add(Rendirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 120, 50));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Timer timer;

    private void contador() {

        timer = new Timer(1000, new ActionListener() {

            int segundos = 0;
            int minutos = 0;

            @Override

            public void actionPerformed(ActionEvent ae) {
                segundos++;
                if (segundos == 60) {
                    minutos++;
                    segundos = 0;
                }
                if (minutos == 10) {

                    Perdiste ventana = new Perdiste();
                    ventana.setVisible(true);
                    timer.stop();
                    dispose();
                }
                if (segundos < 10) {
                    crono2.setText("0" + minutos + ":" + "0" + segundos);
                } else {
                    crono2.setText("0" + minutos + ":" + segundos);
                }

            }

        });
        timer.start();
    }


    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        if (cuatro.isVisible() == false) {
            cuatro.setIcon(uno.getIcon());
            cuatro.setVisible(true);
            uno.setVisible(false);
        }
        if (dos.isVisible() == false) {
            dos.setIcon(uno.getIcon());
            dos.setVisible(true);
            uno.setVisible(false);
        }
        String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
       
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        if (uno.isVisible() == false) {
            uno.setIcon(dos.getIcon());
            uno.setVisible(true);
            dos.setVisible(false);
        }
        if (cinco.isVisible() == false) {
            cinco.setIcon(dos.getIcon());
            cinco.setVisible(true);
            dos.setVisible(false);
        }
        if (tres.isVisible() == false) {
            tres.setIcon(dos.getIcon());
            tres.setVisible(true);
            dos.setVisible(false);
        }
        String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
      
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        if (dos.isVisible() == false) {
            dos.setIcon(tres.getIcon());
            dos.setVisible(true);
            tres.setVisible(false);
        }
        if (seis.isVisible() == false) {
            seis.setIcon(tres.getIcon());
            tres.setVisible(false);
            seis.setVisible(true);
        }
String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
     

    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        if (siete.isVisible() == false) {
            siete.setIcon(cuatro.getIcon());
            cuatro.setVisible(false);
            siete.setVisible(true);
        }
        if (cinco.isVisible() == false) {
            cinco.setIcon(cuatro.getIcon());
            cinco.setVisible(true);
            cuatro.setVisible(false);
        }
        if (uno.isVisible() == false) {
            uno.setIcon(cuatro.getIcon());
            uno.setVisible(true);
            cuatro.setVisible(false);
        }
String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
     

    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        if (ocho.isVisible() == false) {
            ocho.setIcon(cinco.getIcon());
            ocho.setVisible(true);
            cinco.setVisible(false);
        }
        if (cuatro.isVisible() == false) {
            cuatro.setIcon(cinco.getIcon());
            cuatro.setVisible(true);
            cinco.setVisible(false);
        }
        if (seis.isVisible() == false) {
            seis.setIcon(cinco.getIcon());
            seis.setVisible(true);
            cinco.setVisible(false);
        }
        if (dos.isVisible() == false) {
            dos.setIcon(cinco.getIcon());
            dos.setVisible(true);
            cinco.setVisible(false);
        }
        String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
       


    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        if (nueve.isVisible() == false) {
            nueve.setIcon(seis.getIcon());
            seis.setVisible(false);
            nueve.setVisible(true);
        }
        if (cinco.isVisible() == false) {
            cinco.setIcon(seis.getIcon());
            cinco.setVisible(true);
            seis.setVisible(false);
        }
        if (tres.isVisible() == false) {
            tres.setIcon(seis.getIcon());
            tres.setVisible(true);
            seis.setVisible(false);
        }
        String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
     

    }//GEN-LAST:event_seisActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed

        if (ocho.isVisible() == false) {
            ocho.setIcon(siete.getIcon());
            ocho.setVisible(true);
            siete.setVisible(false);
        }
        if (cuatro.isVisible() == false) {
            cuatro.setIcon(siete.getIcon());
            cuatro.setVisible(true);
            siete.setVisible(false);
        }
        String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
     
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        if (nueve.isVisible() == false) {
            nueve.setIcon(ocho.getIcon());
            ocho.setVisible(false);
            nueve.setVisible(true);
        }
        if (siete.isVisible() == false) {
            siete.setIcon(ocho.getIcon());
            ocho.setVisible(false);
            siete.setVisible(true);
        }
        if (cinco.isVisible() == false) {
            cinco.setIcon(ocho.getIcon());
            cinco.setVisible(true);
            ocho.setVisible(false);
        }
        String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
    

    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        if (seis.isVisible() == false) {
            seis.setIcon(nueve.getIcon());
            seis.setVisible(true);
            nueve.setVisible(false);
        }
        if (ocho.isVisible() == false) {
            ocho.setIcon(nueve.getIcon());
            ocho.setVisible(true);
            nueve.setVisible(false);
        }
String casilla1 = "" + uno.getIcon();
        String casilla2 = "" + dos.getIcon();
        String casilla3 = "" + tres.getIcon();
        String casilla4 = "" + cuatro.getIcon();
        String casilla5 = "" + cinco.getIcon();
        String casilla6 = "" + seis.getIcon();
        String casilla7 = "" + siete.getIcon();
        String casilla8 = "" + ocho.getIcon();
        String casilla9 = "" + nueve.getIcon();
        
        int contador=0;

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/9.jpg".equals(casilla1)) {
            System.out.println("correcto1");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/8.jpg".equals(casilla2)) {
            System.out.println("correcto2");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/7.jpg".equals(casilla3)) {
            System.out.println("correcto3");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/6.jpg".equals(casilla4)) {
            System.out.println("correcto4");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/5.jpg".equals(casilla5)) {
            System.out.println("correcto5");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/4.jpg".equals(casilla6)) {
            System.out.println("correcto6");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/3.jpg".equals(casilla7)) {
            System.out.println("correcto7");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/2.jpg".equals(casilla8)) {
            System.out.println("correcto8");
            contador++;
        }

        if ("file:/C:/Users/Adrian_Alejandro/OneDrive/Documentos/NetBeansProjects/Juego%20POO/build/classes/imagenes/1.jpg".equals(casilla9)) {
            System.out.println("correcto9");
            contador++;
        }
        if(contador==8){
            System.out.println("terminado");
            Ganaste ventana= new Ganaste();
            ventana.setVisible(true);
            dispose();
            
        }
    

    }//GEN-LAST:event_nueveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        contador();
        uno.setVisible(true);
        dos.setVisible(true);
        tres.setVisible(true);
        cuatro.setVisible(true);
        cinco.setVisible(true);
        seis.setVisible(true);
        siete.setVisible(true);
        ocho.setVisible(true);
        Iniciar.setEnabled(false);
        Rendirse.setVisible(true);

    }//GEN-LAST:event_IniciarActionPerformed

    private void RendirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RendirseActionPerformed
        Perdiste ventana= new Perdiste();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_RendirseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Rendirse;
    private javax.swing.JButton cinco;
    private javax.swing.JLabel crono2;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JLabel perdio;
    private javax.swing.JLabel perdio1;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables

    private Icon setIconImages(String fileCUsersAdrian_AlejandroDocumentsNetBea) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
